variables:
  # Common variables to be able to build and push docker images
  # https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-disabled
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ''

  # To make npm test to not to start in watc  h mode
  # https://create-react-app.dev/docs/running-tests/#continuous-integration
  CI: 'true'

cache:
  paths:
    - node_modules/

stages:
  - test
  - package

test:
  image: docker.atixlabs.com/node:16.16.0-alpine

  variables:
    NODE_ENV: test

  stage: test
  script:
    - npm install
    - npm run lint
    - npm run test:unit
  except:
    - schedules

package:
  image: docker.atixlabs.com/node:16.16.0-alpine
  services:
    - docker:19.03.1-dind
  stage: package
  script:
    - apk add docker git
    - docker login -u gitlabci -p $CI_JOB_TOKEN $CI_REGISTRY
    - npm cache clean --force
    - npm run docker:build
    - npm run docker:push

  only:
    refs:
      # Only run on develop, main
      - develop
      - main
