openapi: 3.0.3
info:
  title: Cardano off-chain metadata - OpenAPI 3.0
  version: 1.0.0
  servers:
    - url: https://localhost:8000/
paths:
  /health:
    get:
      summary: Server healthcheck
      operationId: health-check
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Healthcheck'
        '500':
          description: Server unavailable
  /metadata:
    post:
      summary: Metada object creation
      operationId: metadata-creation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MetadataCreationBody'
        required: true
      responses:
        '201':
          description: Metadata object created
        '500':
          description: Server unavailable
  /metadata/{subject}:
    get:
      summary: Get the full metadata object associated with the provided subject
      operationId: metadata-get-object-by-subject
      parameters:
        - in: path
          name: subject
          schema:
            type: string
          required: true
          description: Subject of the metadata object to get
      responses:
        '200':
          description: Metadata object retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MetadataObjectBySubject'
        '404':
          description: Metadata object not found
  /metadata/{subject}/properties:
    get:
      summary: Get all the property names which are available for the metadata object associated with the provided subject
      operationId: metadata-get-property-names
      parameters:
        - in: path
          name: subject
          schema:
            type: string
          required: true
          description: Subject of the metadata object to get properties from
      responses:
        '200':
          description: Metadata object properties retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MetadataObjectPropertyNames'
        '404':
          description: Metadata object not found
components:
  schemas:
    Healthcheck:
      type: object
      properties:
        up:
          type: boolean
          example: true
    MetadataObjectBySubject:
      type: object
      required: ['subject']
      additionalProperties:
        type: object
        required: ['value', 'sequenceNumber', 'signatures']
        properties:
          value:
            type: object
          sequenceNumber:
            type: number
          signatures:
            type: array
            items:
              type: object
              required: ['publicKey', 'signature']
              properties:
                publicKey:
                  type: string
                  format: base16
                  minLength: 64
                  maxLength: 64
                signature:
                  type: string
                  format: base16
                  minLength: 128
                  maxLength: 128
      properties:
        subject:
          type: string
          minLength: 1
          maxLength: 255
        policy:
          type: string
          format: base16
          minLength: 56
          maxLength: 120
        preimage:
          type: object
          requiredProperties: ['alg', 'msg']
          properties:
            alg:
              type: string
              enum: ['sha1', 'sha', 'sha3', 'blake2b', 'blake2s', 'keccak', 'md5']
            msg:
              type: string
              encoding: base16
        name:
          type: string
          maxLength: 50
          minLength: 1
        description:
          type: string
          maxLength: 500
        ticker:
          type: string
          maxLength: 9
          minLength: 2
        decimals:
          type: integer
          minimum: 1
          maximum: 19
        url:
          type: string
          format: uri
          maxLength: 250
        logo:
          type: string
          format: base64
          maxLength: 87400
    MetadataObjectPropertyNames:
      type: array
      items:
        type: string
    MetadataCreationBody:
      type: object
      required: ['subject']
      additionalProperties:
        type: object
        required: ['value', 'sequenceNumber', 'signatures']
        properties:
          value:
            type: object
          sequenceNumber:
            type: number
          signatures:
            type: array
            items:
              type: object
              required: ['publicKey', 'signature']
              properties:
                publicKey:
                  type: string
                  format: base16
                  minLength: 64
                  maxLength: 64
                signature:
                  type: string
                  format: base16
                  minLength: 128
                  maxLength: 128
      properties:
        subject:
          type: string
          minLength: 1
          maxLength: 255
        policy:
          type: string
          format: base16
          minLength: 56
          maxLength: 120
        preimage:
          type: object
          requiredProperties: ['alg', 'msg']
          properties:
            alg:
              type: string
              enum: ['sha1', 'sha', 'sha3', 'blake2b', 'blake2s', 'keccak', 'md5']
            msg:
              type: string
              encoding: base16
        name:
          type: string
          maxLength: 50
          minLength: 1
        description:
          type: string
          maxLength: 500
        ticker:
          type: string
          maxLength: 9
          minLength: 2
        decimals:
          type: integer
          minimum: 1
          maximum: 19
        url:
          type: string
          format: uri
          maxLength: 250
        logo:
          type: string
          format: base64
          maxLength: 87400
